version: '3.8'
services:
  oidc-provider:
    build:
      context: ./oidc_provider
    environment:
      - ISSUER=http://host.docker.internal:3001
      - PORT=3001
    ports:
      - 3001:3001

  oidc-app:
    build:
      context: ./oidc_app
    environment:
      - OIDC_ISSUER=http://host.docker.internal:3001/
      - OIDC_CLIENT_ID=wire-pact
      - OIDC_CLIENT_SECRET=demo-oidc-provider
      - API_URL=http://oidc-api:5000/swapi/people
    networks:
      - app-net
    ports:
      - 3000:3000

  oidc-api:
    build:
      context: ./oidc_api
    environment:
      - OIDC__ISSUER=http://host.docker.internal:3001/
      - OIDC__CLIENTID=wire-pact
      - OIDC__CLIENTSECRET=demo-oidc-provider
    networks:
      - app-net
    ports:
      - 5000:5000

  basic-auth-api:
    build:
      context: ./basic_auth_api
    environment:
      - PORT=8000
      - AUTH_USERNAME=api
      - AUTH_PASSWORD=supersecret
    networks:
      - app-net
    ports:
      - 8000:8000

  basic-auth-app:
    build:
      context: ./basic_auth_app
    environment:
      - PORT=8080
      - AUTH_USER=api
      - AUTH_PASS=supersecret
      - API_URL=http://host.docker.internal:8000/swapi/people
    networks:
      - app-net
    ports:
      - 8080:8080

networks:
  app-net:
    driver: bridge
