version: '3.8'
services:
  oidc-provider:
    image: ghcr.io/wirepact/demo-applications/oidc-provider:latest
    environment:
      - ISSUER=http://localhost:3000
      - PORT=3000
    ports:
      - 3000:3000
