name: Publish Docker Image

on:
  push:
    branches:
      - main

jobs:
  build_images:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        include:
          - context: ./oidc_api
            image: oidc-api
          - context: ./oidc_app
            image: oidc-app
          - context: ./oidc_provider
            image: oidc-provider
          - context: ./basic_auth_api
            image: basic-auth-api

    name: Build ${{ matrix.image }} Docker image

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and Push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.context }}/Dockerfile
          push: true
          build-args: |
            COMMIT_SHA=${{ github.sha }}
          tags: |
            ghcr.io/wirepact/demo-applications/${{ matrix.image }}:latest
            ghcr.io/wirepact/demo-applications/${{ matrix.image }}:${{ github.sha }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
